---

- name: RABBITMQ USERS | Manage users
  rabbitmq_user:
    user: "{{ item.user }}"
    password: "{{ item.password | default('') }}"
    configure_priv: "{{ item.configure_priv | default('.*') }}"
    read_priv: "{{ item.read_priv | default('.*') }}"
    write_priv: "{{ item.write_priv | default('.*') }}"
    vhost: "{{ item.vhost | default('/') }}"
    tags: "{{ item.tags | default('') }}"
    state: "{{ item.state | default('present') }}"
  with_items: "{{ rabbitmq_users }}"
